apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: stackrox
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: stackrox-admission-control
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: stackrox-collector
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: stackrox-sensor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackrox:create-events-binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackrox:enforce-policies
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackrox:monitor-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackrox:network-policies-binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackrox:review-tokens-binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackrox:update-namespaces-binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox-admission-control-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox-collector-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox-sensor-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox:create-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox:edit-workloads
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox:network-policies
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox:review-tokens
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox:update-namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackrox:view-cluster
# namespace-scoped resources follow
---
# TODO(ROX-11020): find what creates this configmap and why it's not getting cleaned up
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: admission-control
#---
apiVersion: v1
kind: ConfigMap
metadata:
  name: injected-cabundle-stackrox-secured-cluster-services
---
apiVersion: v1
kind: Endpoints
metadata:
  name: admission-control
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sensor
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sensor-webhook
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-cluster-config
---
apiVersion: v1
kind: Secret
metadata:
  name: service-ca
---
apiVersion: v1
kind: Secret
metadata:
  name: sh.helm.release.v1.stackrox-secured-cluster-services.v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-control
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor
---
apiVersion: v1
kind: Service
metadata:
  name: admission-control
---
apiVersion: v1
kind: Service
metadata:
  name: sensor
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-webhook
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-control
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: admission-control-no-ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: collector-no-ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sensor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admission-control-use-scc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admission-control-watch-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collector-use-scc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-use-scc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-admission-control-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-collector-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-sensor-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-anyuid-scc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-scc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watch-config
